sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=e707e5686481e04d6c46431f003efb49b8fbf31c4f9c2a583db99ae7b58a2774
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - paver develop
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - tox
  - coverage run test_models.py
  - coverage report
after_script:
  - ./cc-test-reporter after-build cc-test-reporter --input-type coverage.py --debug --exit-code $TRAVIS_TEST_RESULT
